// Generated by tools/sync-compatibility.mjs. Do not edit.
namespace NinjaSlayer.Code.Compatibility;

internal static class GeneratedGameHostContracts
{
    private static readonly GameHostContractProfile[] AllProfiles =
    [
        new(
            "stable",
            "0.107.1",
            "STS2.RitsuLib.Compat.0.107.1",
            "0.5.12",
            "public-release",
            "0.1.0.0",
            Guid.Parse("97f10687-c306-4798-ab75-8b9f23f34dfb"),
            new(0x06008154, "93374cd3459eb592a9902b36e2951e3a8edd76149a23b25fa916f8a09d29a193"),
            new(
                PreparedDrawHostLayout.DirectAsync,
                new(0x060084F7, "c74c9285b0c54b84570aede0fcf50f893d147004d5a5ae7ec0cdd248d002df0c"),
                null,
                new(0x0600BF29, "696a9bca0210759f98e13e95ddf36e187b5c23203ca8439a7336d69066212795")),
            new(0x060081C8, "2b9abf44a4a60d409b6144291d8b422647f5790709059c78bfabef19db96c636"),
            new(0x060081C9, "29107e0818dd19bddf4281a9070478c8990728fef97ea02e0a11eda5cbf85f19"),
            new(
                new(0x0600A851, "20e9593fbcfcddf6659c0f0bc02717b7563d1962ba564e97a03049fdc9745713"),
                new(0x0600BF1B, "84801640cd16ce69d93387a0051d21abd77e7799d14d021fa893279cdf70b653"),
                new(0x0600A855, "f3d6c03be54b3478194bdbbf120854a6c65c268197635c4de50135bb67349634"),
                new(0x0600A695, "08db0739e6cf6c79c8961848c1491c56335fb65bd294302dfab0bc97a09671de")),
            new(
                new(0x0600BFA5, "94083afdf65c86d2877f68043d702417a4825a3c1369ab2a0323dd670fdb2cda"),
                new(0x0600C007, "cf9888497aea687ef552a6550bb501f1892674608eac277051a484c9de23fd43"),
                new(0x0600C00B, "91071711a0e4db073dbf1f5be40aebadb59947e16a10465e82bf68deba0e7f85"))),
        new(
            "preview",
            "0.111.0",
            "STS2.RitsuLib",
            "0.5.12",
            "public-test",
            "0.1.0.0",
            Guid.Parse("73b63ee0-6c0a-47bb-b0d1-b21f6d94222e"),
            new(0x060051D6, "182071e17dcc0a73602518f69201200653bd0c6b17831d1cabe79081e64b0412"),
            new(
                PreparedDrawHostLayout.WrapperWithAsyncInternal,
                new(0x060055A0, "c10b8eebbec586cf9f681ab00c5924d66302283d48eabf6c9ad0d43ebb89c530"),
                new(0x060055A2, "153adbee13a84b5f0236658dc282bc3ca186c4bd6b0f2eaaeff4da7dfbf6bf18"),
                new(0x0600B272, "ea766a8b5ba0ea62d5faa107ad830e3e8dfdaee88855479dc3a11e7986ec10c7")),
            new(0x06005253, "82423be2ded8f470d6586b8360e4d7932e8bcbf21e698feef8eb698ec6b8b24f"),
            new(0x06005254, "42e1c1b31fd46ff94e09573c2d06dfcb8f8fec03ee86f9bc5efd3985fba79269"),
            new(
                new(0x06009B06, "1ffd5acae50bbf8394922bb58b1d00646e1968aafbd4fa68abf926d9d839fa53"),
                new(0x0600B264, "65bcafd3be1b66acd26fd13da6b2a2bf1611657966616038c19e71ab34c88012"),
                new(0x06009B08, "8e57746fbab845d08ce5439bcd633c6341c9512d76bacd7da52c876dc7565023"),
                new(0x0600C886, "c8cb6cb9307b3c91f94554900c23e57e523f3929b656a33385e654283bed65b6")),
            new(
                new(0x0600B2F1, "8d932ee05b80edcffed77d180bf39c1a679f48b65874103badfc9e8e2828d5bc"),
                new(0x0600B353, "a2e6554ea582782359fe2969d9c77eedd64776cc983840d818f742de2c6af0ab"),
                new(0x0600B357, "a8999376dffc0bfff0cbaa42db95b6d9605f0e2892a5745e50a377dd7e9cd41b")))
    ];

    public static IReadOnlyList<GameHostContractProfile> All { get; } =
        Array.AsReadOnly(AllProfiles);

    public static IReadOnlyList<GameHostContractProfile> Current { get; } =
        Array.AsReadOnly<GameHostContractProfile>(
        [
#if NINJASLAYER_CHANNEL_STABLE
        AllProfiles[0]
#elif NINJASLAYER_CHANNEL_PREVIEW
        AllProfiles[1]
#else
#error NinjaSlayer host channel symbol was not generated.
#endif
        ]);
}
