// Generated by tools/sync-compatibility.mjs. Do not edit.
namespace NinjaSlayer.Code.Compatibility;

internal static class GeneratedGameHostContracts
{
    private static readonly GameHostContractProfile[] AllProfiles =
    [
        new(
            "stable",
            "0.107.1",
            "STS2.RitsuLib.Compat.0.107.1",
            "0.5.1",
            "public-release",
            "0.1.0.0",
            Guid.Parse("97f10687-c306-4798-ab75-8b9f23f34dfb"),
            new(0x06008154, "93374cd3459eb592a9902b36e2951e3a8edd76149a23b25fa916f8a09d29a193"),
            new(
                PreparedDrawHostLayout.DirectAsync,
                new(0x060084F7, "c74c9285b0c54b84570aede0fcf50f893d147004d5a5ae7ec0cdd248d002df0c"),
                null,
                new(0x0600BF29, "696a9bca0210759f98e13e95ddf36e187b5c23203ca8439a7336d69066212795")),
            new(0x060081C8, "2b9abf44a4a60d409b6144291d8b422647f5790709059c78bfabef19db96c636"),
            new(0x060081C9, "29107e0818dd19bddf4281a9070478c8990728fef97ea02e0a11eda5cbf85f19")),
        new(
            "preview",
            "0.110.1",
            "STS2.RitsuLib",
            "0.5.1",
            "public-test",
            "0.1.0.0",
            Guid.Parse("c0f649b8-8d57-4a9c-8b07-21aece97dca0"),
            new(0x0600522F, "8ef02d18f507abaf34438d126c58b86dcf892e271304ab878d7363a79a8b6fcf"),
            new(
                PreparedDrawHostLayout.WrapperWithAsyncInternal,
                new(0x060055F7, "c441fbd17225889f4d7af6bf5ca2e0ca25a572c3946bcef6e218d991314d9a58"),
                new(0x060055F9, "e4b5eeaa5eaa3ebc953b80f66cf19c5bcebffed54516f32f6e713b884632e4df"),
                new(0x0600B20E, "e708542e1f0e31e6427962848d2847a0bbf1782772b8469c9f4392bfdfabac1b")),
            new(0x060052AC, "30a9338c827ca52914c892372e1a21f133dd02300f49dbddf9f9abaf959751bc"),
            new(0x060052AD, "a28a8b361c7e433cc5254b54645155b5448468d132ace669b19e16fc59c45afd"))
    ];

    public static IReadOnlyList<GameHostContractProfile> All { get; } =
        Array.AsReadOnly(AllProfiles);

    public static IReadOnlyList<GameHostContractProfile> Current { get; } =
        Array.AsReadOnly<GameHostContractProfile>(
        [
#if NINJASLAYER_CHANNEL_STABLE
        AllProfiles[0]
#elif NINJASLAYER_CHANNEL_PREVIEW
        AllProfiles[1]
#else
#error NinjaSlayer host channel symbol was not generated.
#endif
        ]);
}
